name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t toppo918/multi-docker -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true toppo918/multi-docker npm run test

      - run: docker build -t toppo918/multi-client ./client
      - run: docker build -t toppo918/multi-nginx ./nginx
      - run: docker build -t toppo918/multi-server ./server
      - run: docker build -t toppo918/multi-worker ./worker

      - run: docker push toppo918/multi-client
      - run: docker push toppo918/multi-nginx
      - run: docker push toppo918/multi-server
      - run: docker push toppo918/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-014416654561
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

